version: "3"
services:
    frontend:
        container_name: cat_app_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: anupam/cat_app_frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/usr/src/app
    backend:
        container_name: cat_app_backend
        build:
            context: ./
            dockerfile: Dockerfile
        image: anupam/cat_app_backend
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app
